/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.Produto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Qualidade
 */
public class DimensionalFrame extends javax.swing.JDialog {
   
    /**
     * Creates new form DimensionalFrame
     * @param parent
     * @param modal
     */
    public DimensionalFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        item.setText(Cadastro.getInstancia().getItem().getCodigo() + " - " + Cadastro.getInstancia().getItem().getDescricao());
        setTitle(Cadastro.getInstancia().getItem().getCodigo() + " - " + Cadastro.getInstancia().getItem().getDescricao() + " -Dimensional");
        atualizar();
    }

    private void atualizar(){
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        Object[] s = {"s (chave)", Cadastro.getInstancia().getItem().getDimensional().getS(),Cadastro.getInstancia().getItem().getDimensional().getsMin(),Cadastro.getInstancia().getItem().getDimensional().getsMAx()};
        model.addRow(s);
        
        Object[] h = {"h (altura cabeça)", Cadastro.getInstancia().getItem().getDimensional().getH(),Cadastro.getInstancia().getItem().getDimensional().gethMin(),Cadastro.getInstancia().getItem().getDimensional().gethMax()};
        model.addRow(h);
        
        Object[] D = {"D (diametro cabeça)", Cadastro.getInstancia().getItem().getDimensional().getD(),Cadastro.getInstancia().getItem().getDimensional().getDMin(),Cadastro.getInstancia().getItem().getDimensional().getDMax()};
        model.addRow(D);
        
        Object[] b = {"b (compr. rosca)", Cadastro.getInstancia().getItem().getDimensional().getB(),Cadastro.getInstancia().getItem().getDimensional().getbMin(),Cadastro.getInstancia().getItem().getDimensional().getbMax()};
        model.addRow(b);
        
        Object[] l = {"l (comprimento)", Cadastro.getInstancia().getItem().getDimensional().getL(),Cadastro.getInstancia().getItem().getDimensional().getlMin(),Cadastro.getInstancia().getItem().getDimensional().getlMax()};
        model.addRow(l);
        
        Object[] d = {"d (diametro)", Cadastro.getInstancia().getItem().getDimensional().getd(),Cadastro.getInstancia().getItem().getDimensional().getdMin(),Cadastro.getInstancia().getItem().getDimensional().getdMax()};
        model.addRow(d);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        unidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chavePol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        item.setText("jLabel1");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nominal", "Minimo", "Maximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Unidade :");

        jLabel2.setText("Chave Pol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chavePol, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(chavePol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chavePol;
    private javax.swing.JLabel item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField unidade;
    // End of variables declaration//GEN-END:variables
}
