/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Produto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Qualidade
 */
public class FisicaFrame extends javax.swing.JDialog {

    /**
     * Creates new form FisicaFrame
     *
     * @param parent
     * @param modal
     */
    public FisicaFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        String titulo = Cadastro.getInstancia().getItem().getCodigo() + " - " + Cadastro.getInstancia().getItem().getDescricao();
        initComponents();
        setTitle(titulo);
        produto.setText(titulo);
        criar();
    }

    private void criar() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        model.setNumRows(0);
        
        Object[] dureza = {"Dureza", Cadastro.getInstancia().getItem().getFisica().getDurezaUni(), Cadastro.getInstancia().getItem().getFisica().getDurezaMin(), Cadastro.getInstancia().getItem().getFisica().getDurezaMax()};
        model.addRow(dureza);

        Object[] resistencia = {"Resistencia a tracao", Cadastro.getInstancia().getItem().getFisica().getResistenciaUnid(), Cadastro.getInstancia().getItem().getFisica().getResistenciaMin(), Cadastro.getInstancia().getItem().getFisica().getResistenciaMax()};
        model.addRow(resistencia);

        Object[] tensao = {"Tensao escoamento", Cadastro.getInstancia().getItem().getFisica().getTensaoUni(), Cadastro.getInstancia().getItem().getFisica().getTensaoMin(), Cadastro.getInstancia().getItem().getFisica().getTensaoMax()};
        model.addRow(tensao);

        Object[] alongam = {"Alongamento", Cadastro.getInstancia().getItem().getFisica().getAlongamUni(), Cadastro.getInstancia().getItem().getFisica().getAlongamMin(), Cadastro.getInstancia().getItem().getFisica().getAlongamMax()};
        model.addRow(alongam);

        Object[] estric = {"Estricção", Cadastro.getInstancia().getItem().getFisica().getEstricUni(), Cadastro.getInstancia().getItem().getFisica().getEstricMin(), Cadastro.getInstancia().getItem().getFisica().getEstricMax()};
        model.addRow(estric);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        produto.setText("jLabel1");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propriedade", "Unidade", "Minimo", "Maximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Valor: " + (String) tabela.getValueAt(0, 1));
        Cadastro.getInstancia().getItem().getFisica().setDurezaUni((String) tabela.getValueAt(0, 1));
        Cadastro.getInstancia().getItem().getFisica().setDurezaMin((float) tabela.getValueAt(0, 2));
        Cadastro.getInstancia().getItem().getFisica().setDurezaMax((float) tabela.getValueAt(0, 3));

        Cadastro.getInstancia().getItem().getFisica().setResistenciaUnid((String) tabela.getValueAt(1, 1));
        Cadastro.getInstancia().getItem().getFisica().setResistenciaMin((float) tabela.getValueAt(1, 2));
        Cadastro.getInstancia().getItem().getFisica().setResistenciaMax((float) tabela.getValueAt(1, 3));

        Cadastro.getInstancia().getItem().getFisica().setTensaoUni((String) tabela.getValueAt(2, 1));
        Cadastro.getInstancia().getItem().getFisica().setTensaoMin((float) tabela.getValueAt(2, 2));
        Cadastro.getInstancia().getItem().getFisica().setTensaoMax((float) tabela.getValueAt(2, 3));

        Cadastro.getInstancia().getItem().getFisica().setAlongamUni((String) tabela.getValueAt(3, 1));
        Cadastro.getInstancia().getItem().getFisica().setAlongamMin((float) tabela.getValueAt(3, 2));
        Cadastro.getInstancia().getItem().getFisica().setAlongamMax((float) tabela.getValueAt(3, 3));

        Cadastro.getInstancia().getItem().getFisica().setEstricUni((String) tabela.getValueAt(4, 1));
        Cadastro.getInstancia().getItem().getFisica().setEstricMin((float) tabela.getValueAt(4, 2));
        Cadastro.getInstancia().getItem().getFisica().setEstricMax((float) tabela.getValueAt(4, 3));

        Cadastro.getInstancia().getItem().salvar();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel produto;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
