/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Produto;

import Cadastro.Aco;
import Cadastro.Material;
import GUI.Principal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Qualidade
 */
public class MaterialFrame extends javax.swing.JInternalFrame {

    private int indexx = 0;
    private Aco aco;

    /**
     * Creates new form MaterialFrame
     */
    public MaterialFrame() {
        initComponents();
        
        
        atualizar();
    }

    private void atualizar() {
        try {
            aco = Material.getInstancia().getMaterial(indexx);
        } catch (Exception e) {
            aco = Material.getInstancia().vazio();
        }
        index.setText(String.valueOf(indexx));
        nome.setText(aco.getNome());
        grau.setText(aco.getGrau());
        bitola.setText(aco.getBitola());

        DefaultTableModel model = (DefaultTableModel) quimica.getModel();
        
        model.setNumRows(0);
        
        Object[] c = {"C", aco.getQuimica().getcMim(), aco.getQuimica().getcMax()};
        model.addRow(c);

        Object[] mn = {"Mn", aco.getQuimica().getMnMin(), aco.getQuimica().getMnMax()};
        model.addRow(mn);

        Object[] p = {"P", aco.getQuimica().getpMin(), aco.getQuimica().getpMax()};
        model.addRow(p);

        Object[] s = {"S", aco.getQuimica().getsMin(), aco.getQuimica().getsMax()};
        model.addRow(s);

        Object[] b = {"B", aco.getQuimica().getbMin(), aco.getQuimica().getbMax()};
        model.addRow(b);

        Object[] si = {"Si", aco.getQuimica().getSiMin(), aco.getQuimica().getSiMax()};
        model.addRow(si);

        Object[] cr = {"Cr", aco.getQuimica().getCrMin(), aco.getQuimica().getCrMax()};
        model.addRow(cr);

        Object[] mo = {"Mo", aco.getQuimica().getMoMin(), aco.getQuimica().getMoMax()};
        model.addRow(mo);

        Object[] ni = {"Ni", aco.getQuimica().getNiMin(), aco.getQuimica().getNiMax()};
        model.addRow(ni);

        Object[] v = {"V", aco.getQuimica().getvMin(), aco.getQuimica().getvMax()};
        model.addRow(v);

        DefaultTableModel model2 = (DefaultTableModel) fisica.getModel();

        model2.setNumRows(0);
        
        Object[] dureza = {"Dureza", aco.getFisica().getDurezaUni(), aco.getFisica().getDurezaMin(), aco.getFisica().getDurezaMax()};
        model2.addRow(dureza);

        Object[] resistencia = {"Resistencia a tracao", aco.getFisica().getResistenciaUnid(), aco.getFisica().getResistenciaMin(), aco.getFisica().getResistenciaMax()};
        model2.addRow(resistencia);

        Object[] tensao = {"Tensao escoamento", aco.getFisica().getTensaoUni(), aco.getFisica().getTensaoMin(), aco.getFisica().getTensaoMax()};
        model2.addRow(tensao);

        Object[] alongam = {"Alongamento", aco.getFisica().getAlongamUni(), aco.getFisica().getAlongamMin(), aco.getFisica().getAlongamMax()};
        model2.addRow(alongam);

        Object[] estric = {"Estricção", aco.getFisica().getEstricUni(), aco.getFisica().getEstricMin(), aco.getFisica().getEstricMax()};
        model2.addRow(estric);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        grau = new javax.swing.JTextField();
        bitola = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        quimica = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        fisica = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        index = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Material");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Proximo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Anterior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome: ");

        jLabel2.setText("Grau:");

        jLabel3.setText("Bitola:");

        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });

        grau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                grauFocusLost(evt);
            }
        });

        bitola.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bitolaFocusLost(evt);
            }
        });

        quimica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Elemento", "Minimo", "Maximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(quimica);

        fisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Propriedade", "Unidade", "Minimo", "Maximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(fisica);

        jLabel4.setText("Quimica:");

        jLabel5.setText("Fisica: ");

        jButton5.setText("Listar");

        index.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(300, 300, 300)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome)
                            .addComponent(grau)
                            .addComponent(bitola, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(index)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(index))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(grau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bitola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        Principal.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        // TODO add your handling code here:
        aco.setNome(nome.getText());
    }//GEN-LAST:event_nomeFocusLost

    private void grauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grauFocusLost
        // TODO add your handling code here:
        aco.setGrau(grau.getText());
    }//GEN-LAST:event_grauFocusLost

    private void bitolaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bitolaFocusLost
        // TODO add your handling code here:
        aco.setBitola(bitola.getText());
    }//GEN-LAST:event_bitolaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        aco.getQuimica().setcMim((float) quimica.getValueAt(0, 1));
        aco.getQuimica().setcMax((float) quimica.getValueAt(0, 2));

        aco.getQuimica().setMnMin((float) quimica.getValueAt(1, 1));
        aco.getQuimica().setMnMax((float) quimica.getValueAt(1, 2));

        aco.getQuimica().setpMin((float) quimica.getValueAt(2, 1));
        aco.getQuimica().setpMax((float) quimica.getValueAt(2, 2));

        aco.getQuimica().setsMin((float) quimica.getValueAt(3, 1));
        aco.getQuimica().setsMax((float) quimica.getValueAt(3, 2));

        aco.getQuimica().setbMin((float) quimica.getValueAt(4, 1));
        aco.getQuimica().setbMax((float) quimica.getValueAt(4, 2));

        aco.getQuimica().setSiMin((float) quimica.getValueAt(5, 1));
        aco.getQuimica().setSiMax((float) quimica.getValueAt(5, 2));

        aco.getQuimica().setCrMin((float) quimica.getValueAt(6, 1));
        aco.getQuimica().setCrMax((float) quimica.getValueAt(6, 2));

        aco.getQuimica().setMoMin((float) quimica.getValueAt(7, 1));
        aco.getQuimica().setMoMax((float) quimica.getValueAt(7, 2));

        aco.getQuimica().setNiMin((float) quimica.getValueAt(8, 1));
        aco.getQuimica().setNiMax((float) quimica.getValueAt(8, 2));

        aco.getQuimica().setvMin((float) quimica.getValueAt(9, 1));
        aco.getQuimica().setvMax((float) quimica.getValueAt(9, 2));

        aco.getFisica().setDurezaUni((String) fisica.getValueAt(0, 1));
        aco.getFisica().setDurezaMin((float) fisica.getValueAt(0, 2));
        aco.getFisica().setDurezaMax((float) fisica.getValueAt(0, 3));

        aco.getFisica().setResistenciaUnid((String) fisica.getValueAt(1, 1));
        aco.getFisica().setResistenciaMin((float) fisica.getValueAt(1, 2));
        aco.getFisica().setResistenciaMax((float) fisica.getValueAt(1, 3));

        aco.getFisica().setTensaoUni((String) fisica.getValueAt(2, 1));
        aco.getFisica().setTensaoMin((float) fisica.getValueAt(2, 2));
        aco.getFisica().setTensaoMax((float) fisica.getValueAt(2, 3));

        aco.getFisica().setAlongamUni((String) fisica.getValueAt(3, 1));
        aco.getFisica().setAlongamMin((float) fisica.getValueAt(3, 2));
        aco.getFisica().setAlongamMax((float) fisica.getValueAt(3, 3));

        aco.getFisica().setEstricUni((String) fisica.getValueAt(4, 1));
        aco.getFisica().setEstricMin((float) fisica.getValueAt(4, 2));
        aco.getFisica().setEstricMax((float) fisica.getValueAt(4, 3));

        Material.getInstancia().addMaterial(aco);
        Material.getInstancia().salvar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (indexx < Material.getInstancia().getLeght()) {
            indexx++;
            atualizar();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if (indexx > 0) {
            indexx--;
            atualizar();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Material.getInstancia().retirar(indexx);
        Material.getInstancia().salvar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bitola;
    private javax.swing.JTable fisica;
    private javax.swing.JTextField grau;
    private javax.swing.JLabel index;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nome;
    private javax.swing.JTable quimica;
    // End of variables declaration//GEN-END:variables
}
