/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Produto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Qualidade
 */
public class QuimicaFrame extends javax.swing.JDialog {



    /**
     * Creates new form Quimica
     *
     * @param parent
     * @param modal
     */
    public QuimicaFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        String titulo = Cadastro.getInstancia().getItem().getCodigo() + " - " + Cadastro.getInstancia().getItem().getDescricao();
        initComponents();
        this.item.setText(titulo);
        this.setTitle(titulo + " -Quimica");
        carregar();
    }
    /*
     c
     mn
     p
     s
     b
     si
     cr
     mo
     ni
     v
     */

    private void carregar() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        model.setNumRows(0);
        
        Object[] c = {"C",Cadastro.getInstancia().getItem().getQuimica().getcMim(),Cadastro.getInstancia().getItem().getQuimica().getcMax()};
        model.addRow(c);
        
        Object[] mn = {"Mn",Cadastro.getInstancia().getItem().getQuimica().getMnMin(),Cadastro.getInstancia().getItem().getQuimica().getMnMax()};
        model.addRow(mn);
        
        Object[] p = {"P",Cadastro.getInstancia().getItem().getQuimica().getpMin(),Cadastro.getInstancia().getItem().getQuimica().getpMax()};
        model.addRow(p);
        
        Object[] s = {"S",Cadastro.getInstancia().getItem().getQuimica().getsMin(),Cadastro.getInstancia().getItem().getQuimica().getsMax()};
        model.addRow(s);
        
        Object[] b = {"B",Cadastro.getInstancia().getItem().getQuimica().getbMin(),Cadastro.getInstancia().getItem().getQuimica().getbMax()};
        model.addRow(b);
        
        Object[] si = {"Si",Cadastro.getInstancia().getItem().getQuimica().getSiMin(),Cadastro.getInstancia().getItem().getQuimica().getSiMax()};
        model.addRow(si);
        
        Object[] cr = {"Cr",Cadastro.getInstancia().getItem().getQuimica().getCrMin(),Cadastro.getInstancia().getItem().getQuimica().getCrMax()};
        model.addRow(cr);
        
        Object[] mo = {"Mo",Cadastro.getInstancia().getItem().getQuimica().getMoMin(),Cadastro.getInstancia().getItem().getQuimica().getMoMax()};
        model.addRow(mo);
        
        Object[] ni = {"Ni",Cadastro.getInstancia().getItem().getQuimica().getNiMin(),Cadastro.getInstancia().getItem().getQuimica().getNiMax()};
        model.addRow(ni);
        
        Object[] v = {"V",Cadastro.getInstancia().getItem().getQuimica().getvMin(),Cadastro.getInstancia().getItem().getQuimica().getvMax()};
        model.addRow(v);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Elemento", "Minimo", "Maximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Cadastro.getInstancia().getItem().getQuimica().setcMim((float)tabela.getValueAt(0, 1));
       Cadastro.getInstancia().getItem().getQuimica().setcMax((float)tabela.getValueAt(0, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setMnMin((float)tabela.getValueAt(1, 1));
       Cadastro.getInstancia().getItem().getQuimica().setMnMax((float)tabela.getValueAt(1, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setpMin((float)tabela.getValueAt(2, 1));
       Cadastro.getInstancia().getItem().getQuimica().setpMax((float)tabela.getValueAt(2, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setsMin((float)tabela.getValueAt(3, 1));
       Cadastro.getInstancia().getItem().getQuimica().setsMax((float)tabela.getValueAt(3, 2));
              
       Cadastro.getInstancia().getItem().getQuimica().setbMin((float)tabela.getValueAt(4, 1));
       Cadastro.getInstancia().getItem().getQuimica().setbMax((float)tabela.getValueAt(4, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setSiMin((float)tabela.getValueAt(5, 1));
       Cadastro.getInstancia().getItem().getQuimica().setSiMax((float)tabela.getValueAt(5, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setCrMin((float)tabela.getValueAt(6, 1));
       Cadastro.getInstancia().getItem().getQuimica().setCrMax((float)tabela.getValueAt(6, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setMoMin((float)tabela.getValueAt(7, 1));
       Cadastro.getInstancia().getItem().getQuimica().setMoMax((float)tabela.getValueAt(7, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setNiMin((float)tabela.getValueAt(8, 1));
       Cadastro.getInstancia().getItem().getQuimica().setNiMax((float)tabela.getValueAt(8, 2));
       
       Cadastro.getInstancia().getItem().getQuimica().setvMin((float)tabela.getValueAt(9, 1));
       Cadastro.getInstancia().getItem().getQuimica().setvMax((float)tabela.getValueAt(9, 2));
       
       Cadastro.getInstancia().getItem().salvar();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
     public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     *
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(QuimicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(QuimicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(QuimicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(QuimicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     Create and display the dialog 
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     QuimicaFrame dialog = new QuimicaFrame(new javax.swing.JFrame(), true);
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
     System.exit(0);
     }
     });
     dialog.setVisible(true);
     }
     });
     }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
